name: mi_card
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^6.1.1
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - images/test.png

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/DotGothic16-Regular.ttf
    - family: Gothic
      fonts:
        - asset: fonts/Roboto-Regular.ttf
